$ErrorActionPreference = 'Stop'

# Remove volatile build data but keep WinRM available until Packer initiates
# the final shutdown. vSphere guest customization or the post-clone Ansible
# role is responsible for final identity, domain membership and policy.
Get-ChildItem 'C:\Windows\Temp' -Force -ErrorAction SilentlyContinue | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
Get-ChildItem "$env:TEMP" -Force -ErrorAction SilentlyContinue | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue

Get-EventLog -LogName * -ErrorAction SilentlyContinue | ForEach-Object {
    Clear-EventLog -LogName $_.Log -ErrorAction SilentlyContinue
}

# Reset common deployment identifiers that should be regenerated by the clone.
Remove-Item 'C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys\*' -Force -ErrorAction SilentlyContinue

Write-Host 'Windows image cleanup complete; ready for template conversion.'
